plugin-jdbc-postgres/src/main/java/io/kestra/plugin/jdbc/postgresql/PostgresCellConverter.java
plugin-jdbc-postgres/src/test/java/io/kestra/plugin/jdbc/postgresql/PgsqlTest.java

fix(jdbc-postgres): void types from query are converted to null

---

plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java

fix: allow setting the JDBC URL for MotherDuck

---

plugin-jdbc-duckdb/build.gradle

I'm not a Java developper, sorry if I'm missing something.
Maven: https://central.sonatype.com/artifact/org.duckdb/duckdb_jdbc?smo=true
DuckDB Release: https://duckdb.org/2023/09/26/announcing-duckdb-090.html
I think that Kestra plugins does not need update.
Regards
thomas.

Update DuckDB to 0.9.0

---

plugin-jdbc-clickhouse/src/main/java/io/kestra/plugin/jdbc/clickhouse/BulkInsert.java
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseTest.java

Implemented Bulk Insert #167
---
```yaml
id: clickhouse
namespace: dev
tasks:
id: insert
type: io.kestra.plugin.jdbc.clickhouse.BulkInsert
from: "{{ outputs.query.uri }}"
chunk: 1000 # The size of chunk for every bulk request, default 1000
columns: array of strings # If not provided, ? count need to match the from number of cols
url: jdbc:clickhouse://127.0.0.1:56982/
username: clickhouse
password: ch_passwd
sql: |
INSERT INTO YourTable SETTINGS async_insert=1, wait_for_async_insert=1 values( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
```
---

Add clickHouse Bulk Insert

---

plugin-jdbc-pinot/src/main/java/io/kestra/plugin/jdbc/pinot/Trigger.java

The doc for Pinot trigger had an incorrect mention of waiting on Clickhouse DB, corrected it to be Pinot DB.

fix(pinot): correcting pinot trigger doc

---

plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Query.java
plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Trigger.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcBatch.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQuery.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AutoCommitInterface.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/JdbcConnectionInterface.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/JdbcQueryInterface.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/JdbcStatementInterface.java

Improved docs for plugin-jdbc and plugin-jdbc-arrow-flight

docs: Improve docs in plugin-jdbc and plugin-jdbc-arrow-flight

---

plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Query.java
plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Trigger.java
plugin-jdbc-clickhouse/src/main/java/io/kestra/plugin/jdbc/clickhouse/Trigger.java
plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/Trigger.java
plugin-jdbc-druid/src/main/java/io/kestra/plugin/jdbc/druid/Trigger.java
plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Trigger.java
plugin-jdbc-mysql/src/main/java/io/kestra/plugin/jdbc/mysql/Trigger.java
plugin-jdbc-oracle/src/main/java/io/kestra/plugin/jdbc/oracle/Trigger.java
plugin-jdbc-pinot/src/main/java/io/kestra/plugin/jdbc/pinot/Trigger.java
plugin-jdbc-postgres/src/main/java/io/kestra/plugin/jdbc/postgresql/Trigger.java
plugin-jdbc-redshift/src/main/java/io/kestra/plugin/jdbc/redshift/Trigger.java
plugin-jdbc-rockset/src/main/java/io/kestra/plugin/jdbc/rockset/Trigger.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Trigger.java
plugin-jdbc-sqlite/src/main/java/io/kestra/plugin/jdbc/sqlite/Trigger.java
plugin-jdbc-sqlserver/src/main/java/io/kestra/plugin/jdbc/sqlserver/Trigger.java
plugin-jdbc-trino/src/main/java/io/kestra/plugin/jdbc/trino/Trigger.java
plugin-jdbc-vectorwise/src/main/java/io/kestra/plugin/jdbc/vectorwise/Trigger.java
plugin-jdbc-vertica/src/main/java/io/kestra/plugin/jdbc/vertica/Trigger.java

None of the triggers function if `fetch` is not present in the configuration. Adding `fetch` as `true`, so that the triggered flow can have `trigger.rows` value.
Tested the changes by running the triggers on local setup.

fix(docs): correct trigger examples in plugin-jdbc

---

plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java

In the existing flow, the input file was incorrectly represented as:
`"  in.csv: {{ inputs.csv }}",`
Hence, changed the example to a complete flow example for better understanding.

fix(flow): corrected the flow example for DuckDB Query

---

plugin-jdbc-mysql/src/main/java/io/kestra/plugin/jdbc/mysql/Batch.java
plugin-jdbc-mysql/src/main/java/io/kestra/plugin/jdbc/mysql/MysqlCellConverter.java
plugin-jdbc-mysql/src/test/java/io/kestra/plugin/jdbc/mysql/BatchTest.java
plugin-jdbc-mysql/src/test/java/io/kestra/plugin/jdbc/mysql/MysqlTest.java
plugin-jdbc-mysql/src/test/resources/flows/mysql-listen.yml
plugin-jdbc-mysql/src/test/resources/flows/read_mysql.yaml
plugin-jdbc-mysql/src/test/resources/scripts/mysql_insert.sql

- Added test to mysql for alias query (#255). As aliases was worked already
- Changed mysql converted to convert Instant more correct (#109)
- Implemented Batch (#124). Added logic to addPreparedStatementValue in MysqlCellConverter
---
```yaml
tasks:
- id: create
type: io.kestra.plugin.jdbc.mysql.Query
url: jdbc:mysql://127.0.0.1:3306/
username: mysql_user
password: mysql_passwd
sql: |
CREATE TABLE test (
id SERIAL,
name VARCHAR(10),
address VARCHAR(30),
PRIMARY KEY (id)
);
store: true
- id: query
type: io.kestra.plugin.jdbc.mysql.Query
url: jdbc:mysql://127.0.0.1:3306/
username: mysql_user
password: mysql_passwd
sql: |
SELECT *
FROM xref
LIMIT 1500;
store: true
- id: insert
type: io.kestra.plugin.jdbc.mysql.Batch
from: \"{{ outputs.query.uri }}\"
url: jdbc:mysql://127.0.0.1:3306/ …
```

Mysql - Batch implementation. Test fixes

---

build.gradle
gradle.properties

As 2.7 has a bug on number precison for ION

fix: force Jackson version

---

plugin-jdbc-clickhouse/src/main/java/io/kestra/plugin/jdbc/clickhouse/BulkInsert.java
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseTest.java
plugin-jdbc-clickhouse/src/test/resources/scripts/clickhouse.sql
plugin-jdbc-mysql/src/main/java/io/kestra/plugin/jdbc/mysql/Batch.java
plugin-jdbc-mysql/src/test/java/io/kestra/plugin/jdbc/mysql/BatchTest.java
plugin-jdbc-oracle/src/main/java/io/kestra/plugin/jdbc/oracle/Batch.java
plugin-jdbc-oracle/src/test/java/io/kestra/plugin/jdbc/oracle/BatchTest.java
plugin-jdbc-postgres/src/main/java/io/kestra/plugin/jdbc/postgresql/Batch.java
plugin-jdbc-postgres/src/test/java/io/kestra/plugin/jdbc/postgresql/BatchTest.java
plugin-jdbc-postgres/src/test/resources/scripts/postgres_insert.sql
plugin-jdbc-sqlserver/src/main/java/io/kestra/plugin/jdbc/sqlserver/Batch.java
plugin-jdbc-sqlserver/src/test/java/io/kestra/plugin/jdbc/sqlserver/BatchTest.java
plugin-jdbc-vectorwise/src/main/java/io/kestra/plugin/jdbc/vectorwise/Batch.java
plugin-jdbc-vectorwise/src/test/java/io/kestra/plugin/jdbc/vectorwise/BatchTest.java
plugin-jdbc-vertica/src/main/java/io/kestra/plugin/jdbc/vertica/Batch.java
plugin-jdbc-vertica/src/test/java/io/kestra/plugin/jdbc/vertica/BatchTest.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcBatch.java

- Added new property, that allows not to provide columns names and specifications
- Added new unit tests for plugins that uses AbstractJdbcBatch
- Request from ticket #343
---
```yaml
tasks:
- id: query
type: io.kestra.plugin.jdbc.mysql.Query
url: jdbc:mysql://127.0.0.1:3306/
username: mysql_user
password: mysql_passwd
sql: |
SELECT *
FROM xref
LIMIT 1500;
store: true
- id: update
type: io.kestra.plugin.jdbc.mysql.Batch
from: "{{ outputs.query.uri }}"
url: jdbc:mysql://127.0.0.1:3306/
username: mysql_user
password: mysql_passwd
table: xref
```

Improved the Batch tasks to not require an explicit columns specification

---

plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcBatch.java

fix(jdbc): avoid resource leak when using batching, by closing the PreparedStatement
close  #321

Prevent resource leak by closing the PreparedStatement

---

plugin-jdbc-druid/build.gradle

It avoids dependency divergence between the Druid version and the version used in Kestra

fix(druid): exclude Jackson libs as they are provided by Kestra

---

plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcBaseQuery.java

avoid update queries to be in autoCommit mode due to the STORE type and as a consequences don't commit the updates

fix(jdbc): rollback to fetchType None

---

.github/workflows/main.yml
plugin-jdbc-arrow-flight/build.gradle
plugin-jdbc-as400/build.gradle
plugin-jdbc-redshift/build.gradle
plugin-jdbc-snowflake/build.gradle
plugin-jdbc-sqlserver/build.gradle
plugin-jdbc-trino/build.gradle

chore(deps): bump io.trino:trino-jdbc from 462 to 467 #465
chore(deps): bump net.sf.jt400:jt400 from 20.0.7 to 20.0.8 #464
chore(deps): bump net.snowflake:snowflake-jdbc from 3.19.0 to 3.21.0 #463
chore(deps): bump com.microsoft.sqlserver:mssql-jdbc from 12.8.1.jre11 to 12.9.0.jre11-preview #462
chore(deps): bump org.apache.arrow:flight-sql-jdbc-driver from 17.0.0 to 18.1.0
chore(deps): bump andrcuns/allure-publish-action from 2.8.0 to 2.9.0 #446
chore(deps): bump com.amazon.redshift:redshift-jdbc42 from 2.1.0.30 to 2.1.0.31

chore: bump up driver versions

---

build.gradle
plugin-jdbc-oracle/build.gradle
plugin-jdbc-sqlite/build.gradle
plugin-jdbc-trino/build.gradle

chore(deps): bump org.xerial:sqlite-jdbc from 3.46.1.3 to 3.47.2.0 #479
chore(deps): bump commons-codec:commons-codec from 1.17.1 to 1.17.2 #477
chore(deps): bump io.trino:trino-jdbc from 467 to 468
chore(deps): bump com.oracle.database.jdbc:ojdbc11 from 23.5.0.24.07 to 23.6.0.24.10 #435
chore(deps): bump org.bouncycastle:bcprov-jdk18on from 1.78.1 to 1.79 #429
chore(deps): bump org.bouncycastle:bcpkix-jdk18on from 1.78.1 to 1.79 #428

deps: upgrade dependencies

---

plugin-jdbc-postgres/src/main/java/io/kestra/plugin/jdbc/postgresql/PostgresCellConverter.java
plugin-jdbc-postgres/src/test/java/io/kestra/plugin/jdbc/postgresql/PgsqlTest.java
plugin-jdbc-postgres/src/test/resources/flows/update_postgres.yaml
plugin-jdbc-postgres/src/test/resources/scripts/postgres.sql

Support the [`hstore`](https://www.postgresql.org/docs/current/hstore.html) data type in Postgres, returning the value as a string, closes #538
---
I tested the changes by spinning up a local postgres instance and creating a table with a `hstore` data type and then running a simple query flow 
```sql
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE TABLE products (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
attributes HSTORE
);
INSERT INTO products (name, attributes) VALUES ('Laptop', 'processor=>"Intel i7", RAM=>"16GB"');
```
```yaml
id: hstore
namespace: test
tasks:
- id: query
type: io.kestra.plugin.jdbc.postgresql.Query
url: jdbc:postgresql://172.17.0.2:5432/demo
username: postgres
password: password
sql: SELECT * FROM products
fetchType: FETCH
```
The results from the query are as …

Support hstore data type in postgres

---

.github/workflows/publish-docker-images.yml
dockerfiles/snowflake-cli.Dockerfile

- add a workflow to build and push all Dockerfiles in **docker-images-to-publish** (this workflow is duplicated from [dbt repository](https://github.com/kestra-io/plugin-dbt/blob/master/.github/workflows/packages.yml))
- add a first Dockerfile: snowflake-cli
unlock #551

feat(ci): build and publish a docker image for snowflake-cli

---

plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/DuckDbQueryInterface.java
plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Queries.java
plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java
plugin-jdbc-duckdb/src/test/java/io/kestra/plugin/jdbc/duckdb/DuckDbTest.java
plugin-jdbc-duckdb/src/test/resources/sanity-checks/duck.yaml

unfortunately could not use [JDBC connection properties](https://duckdb.org/docs/stable/clients/java#configuring-connections) because `file_search_path` [is not a DuckDB global option](https://duckdb.org/docs/stable/configuration/overview.html#local-configuration-options)
- fixes #267

feat(duckdb): workingDir syntax not needed anymore for input files

---

plugin-jdbc-oracle/src/main/java/io/kestra/plugin/jdbc/oracle/OracleCellConverter.java
plugin-jdbc-oracle/src/test/java/io/kestra/plugin/jdbc/oracle/OracleTest.java

Oracle cell converter was not handling `ZonedDateTime` conversion to its internal timestamp.
- fixes #529

fix(oracle): handle ZonedDateTime conversion to timestamp
