kestra-io/plugin-jdbc

plugin-jdbc-trino/src/main/java/io/kestra/plugin/jdbc/trino/Query.java

doc(trino): Add example without DDL and clarify info about semicolons

---

plugin-jdbc-duckdb/build.gradle

See https://github.com/duckdb/duckdb/issues/9383

fix: downgrade DuckDB driver to 0.8.1

---

plugin-jdbc-postgres/src/test/resources/flows/update_postgres.yaml

chore: rename input id to input name

---

plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Download.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Query.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Trigger.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Upload.java

This includes both doc correction and example correction for Snowflake jdbc plugin

fix(docs+examples): correcting the docs and examples for Snowflake

---

plugin-jdbc-as400/src/main/java/io/kestra/plugin/jdbc/as400/As400CellConverter.java
plugin-jdbc-as400/src/main/java/io/kestra/plugin/jdbc/as400/Query.java
plugin-jdbc-as400/src/main/java/io/kestra/plugin/jdbc/as400/Trigger.java
plugin-jdbc-as400/src/main/java/io/kestra/plugin/jdbc/as400/package-info.java
plugin-jdbc-as400/src/test/java/io/kestra/plugin/jdbc/as400/As400DriverTest.java

Fixes https://github.com/kestra-io/kestra/issues/3540

fix(plugin-jdbc-as400): wrong package name

---

plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/AbstractSnowflakeConnection.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/SnowflakeInterface.java

Fixes https://github.com/kestra-io/plugin-jdbc/issues/186

feat: snowflake private key

---

plugin-jdbc-clickhouse/src/main/java/io/kestra/plugin/jdbc/clickhouse/Query.java
plugin-jdbc-druid/src/main/java/io/kestra/plugin/jdbc/druid/Query.java

Updates https://github.com/kestra-io/docs/issues/1500

fix(examples): change the example to fetch multiple rows instead of one row

---

build.gradle
plugin-jdbc-arrow-flight/build.gradle
plugin-jdbc-oracle/build.gradle
plugin-jdbc-redshift/build.gradle
plugin-jdbc-snowflake/build.gradle
plugin-jdbc-sqlite/build.gradle
plugin-jdbc-sqlserver/build.gradle
plugin-jdbc-trino/build.gradle

Closes https://github.com/kestra-io/plugin-jdbc/pull/355
Closes https://github.com/kestra-io/plugin-jdbc/pull/347
Closes https://github.com/kestra-io/plugin-jdbc/pull/346
Closes https://github.com/kestra-io/plugin-jdbc/pull/345
Closes https://github.com/kestra-io/plugin-jdbc/pull/344
Closes https://github.com/kestra-io/plugin-jdbc/pull/339
Closes https://github.com/kestra-io/plugin-jdbc/pull/338
Closes https://github.com/kestra-io/plugin-jdbc/pull/337
Closes https://github.com/kestra-io/plugin-jdbc/pull/333

chore: dependencies upgrade

---

plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQuery.java

Fixes https://github.com/kestra-io/kestra/issues/4763

fix: fetchOne error when no results

---

plugin-jdbc-postgres/src/main/java/io/kestra/plugin/jdbc/postgresql/CopyIn.java

- Adjust Postgres CopyIn doc language
- I am pretty sure CopyIn language was language for CopyOut.

Adjust Postgres CopyIn doc language

---

plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/JdbcQueryInterface.java

fix(docs): remove the misplaced bracket

---

plugin-jdbc-db2/src/main/java/io/kestra/plugin/jdbc/db2/Queries.java
plugin-jdbc-db2/src/test/java/io/kestra/plugin/jdbc/db2/DB2QueriesTest.java
plugin-jdbc-db2/src/test/resources/scripts/db2_queries.sql
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/JdbcConnectionInterface.java

feat: add db2 Queries task

---

plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Trigger.java

pass warehouse and database value to the Query task
#364

fix(snowflake): Trigger not working when selecting warehouse

---

plugin-jdbc-redshift/src/test/java/io/kestra/plugin/jdbc/redshift/RedshiftQueriesTest.java
plugin-jdbc-redshift/src/test/resources/scripts/redshift_queries.sql
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Download.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Upload.java
plugin-jdbc-snowflake/src/test/java/io/kestra/plugin/jdbc/snowflake/SnowflakeQueriesTest.java
plugin-jdbc-snowflake/src/test/java/io/kestra/plugin/jdbc/snowflake/SnowflakeTest.java
plugin-jdbc-snowflake/src/test/java/io/kestra/plugin/jdbc/snowflake/SnowflakeTriggerTest.java
plugin-jdbc-snowflake/src/test/java/io/kestra/plugin/jdbc/snowflake/UploadDownloadTest.java
plugin-jdbc-snowflake/src/test/resources/scripts/snowflake_queries.sql
plugin-jdbc-sybase/src/main/java/io/kestra/plugin/jdbc/sybase/Query.java
plugin-jdbc-sybase/src/test/java/io/kestra/plugin/jdbc/sybase/SybaseQueriesTest.java
plugin-jdbc-sybase/src/test/java/io/kestra/plugin/jdbc/sybase/SybaseTest.java
plugin-jdbc-sybase/src/test/java/io/kestra/plugin/jdbc/sybase/SybaseTriggerTest.java
plugin-jdbc-sybase/src/test/resources/scripts/sybase_queries.sql
plugin-jdbc-vertica/src/main/java/io/kestra/plugin/jdbc/vertica/Query.java
plugin-jdbc-vertica/src/test/java/io/kestra/plugin/jdbc/vertica/BatchTest.java
plugin-jdbc-vertica/src/test/java/io/kestra/plugin/jdbc/vertica/VerticaQueriesTest.java
plugin-jdbc-vertica/src/test/java/io/kestra/plugin/jdbc/vertica/VerticaTest.java
plugin-jdbc-vertica/src/test/java/io/kestra/plugin/jdbc/vertica/VerticaTriggerTest.java
plugin-jdbc-vertica/src/test/resources/scripts/vertica_queries.sql
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQueries.java

tests for Queries :
- Redshift
- Snowflake
- Sybase
- Vertica

test(queries): add additional tests

---

plugin-jdbc-mysql/src/test/java/io/kestra/plugin/jdbc/mysql/LoadTest.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcBaseQuery.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQueries.java

remove exception for NONE
make STORE default for fetchType

fix(queries): remove exception when fetchType is NONE

---

plugin-jdbc-mysql/src/test/java/io/kestra/plugin/jdbc/mysql/MysqlTest.java
plugin-jdbc-postgres/src/test/java/io/kestra/plugin/jdbc/postgresql/PgsqlTest.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQuery.java

https://github.com/kestra-io/kestra/issues/6482

fix: return size 0 for fetchOne (FETCH_ONE) when there is no result

---

plugin-jdbc-postgres/build.gradle

chore(deps): bump org.bouncycastle:bcprov-jdk18on from 1.78.1 to 1.79 #429
chore(deps): bump org.bouncycastle:bcpkix-jdk18on from 1.78.1 to 1.79 #428

chore(deps): upgrade bouncycastle for postgres

---

plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Trigger.java
plugin-jdbc-as400/src/main/java/io/kestra/plugin/jdbc/as400/Trigger.java
plugin-jdbc-clickhouse/src/main/java/io/kestra/plugin/jdbc/clickhouse/Trigger.java
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseTest.java
plugin-jdbc-db2/src/main/java/io/kestra/plugin/jdbc/db2/Trigger.java
plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/Trigger.java
plugin-jdbc-druid/src/main/java/io/kestra/plugin/jdbc/druid/Trigger.java
plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Trigger.java
plugin-jdbc-duckdb/src/test/java/io/kestra/plugin/jdbc/duckdb/DuckDbTest.java
plugin-jdbc-mysql/src/main/java/io/kestra/plugin/jdbc/mysql/Trigger.java
plugin-jdbc-mysql/src/test/java/io/kestra/plugin/jdbc/mysql/MysqlTest.java
plugin-jdbc-oracle/src/main/java/io/kestra/plugin/jdbc/oracle/Trigger.java
plugin-jdbc-oracle/src/test/java/io/kestra/plugin/jdbc/oracle/OracleTest.java
plugin-jdbc-pinot/src/main/java/io/kestra/plugin/jdbc/pinot/Query.java
plugin-jdbc-postgres/src/main/java/io/kestra/plugin/jdbc/postgresql/Trigger.java
plugin-jdbc-redshift/src/main/java/io/kestra/plugin/jdbc/redshift/Trigger.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Trigger.java
plugin-jdbc-sqlite/src/main/java/io/kestra/plugin/jdbc/sqlite/Trigger.java
plugin-jdbc-sqlserver/src/main/java/io/kestra/plugin/jdbc/sqlserver/Trigger.java
plugin-jdbc-sybase/src/main/java/io/kestra/plugin/jdbc/sybase/Trigger.java
plugin-jdbc-vectorwise/src/main/java/io/kestra/plugin/jdbc/vectorwise/Trigger.java
plugin-jdbc-vertica/src/main/java/io/kestra/plugin/jdbc/vertica/Trigger.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcBaseQuery.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQueries.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQuery.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcTrigger.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/JdbcQueriesInterface.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/JdbcQueryInterface.java

add parameters binding
keep legacy se of Statement for Query
use PreparedStatement when using parameters

feat: Add parameter binding to the Query tasks and Trigger triggers #376

---

docker-compose-ci.yml
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/AbstractClickHouseTest.java
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseQueriesTest.java
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseTest.java
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseTriggerTest.java
plugin-jdbc-clickhouse/src/test/resources/flows/clickhouse-listen.yml

fixes #504 by added a user to clickhouse
---
---

fix #504: clickhouse now requires a user

---

plugin-jdbc-clickhouse/src/main/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseCellConverter.java
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseTest.java
plugin-jdbc-clickhouse/src/test/resources/scripts/clickhouse.sql

fix: convert uint16 for clickhouse

---

plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQueries.java
plugin-jdbc/src/test/java/io/kestra/plugin/jdbc/AbstractJdbcTriggerTest.java

Fixes #https://github.com/kestra-io/kestra/issues/7546
---
---

fix #7546: NPE when rollback if connection is null

---

plugin-jdbc-oracle/src/main/java/io/kestra/plugin/jdbc/oracle/OracleCellConverter.java

Changes:
- avoid database call overhead (remove clob.length())
- use getCharacterStream over getSubString
- avoid loading all data at once
- avoid unnecessary getColumnTypeName() call
- remove redundant rs.getObject(columnIndex)

fix(plugin-jdbc-oracle): add optimization for reading CLOB/BLOB values

---

plugin-jdbc-sqlite/src/main/java/io/kestra/plugin/jdbc/sqlite/Queries.java
plugin-jdbc-sqlite/src/main/java/io/kestra/plugin/jdbc/sqlite/Query.java
plugin-jdbc-sqlite/src/main/java/io/kestra/plugin/jdbc/sqlite/SqliteQueryInterface.java
plugin-jdbc-sqlite/src/main/java/io/kestra/plugin/jdbc/sqlite/SqliteQueryUtils.java
plugin-jdbc-sqlite/src/test/java/io/kestra/plugin/jdbc/sqlite/SqliteQueriesTest.java
plugin-jdbc-sqlite/src/test/java/io/kestra/plugin/jdbc/sqlite/SqliteTest.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/JdbcConnectionInterface.java

implement output for Sqlite
#480

feat: output sqlite file URI

---

plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/DuckDbCellConverter.java
plugin-jdbc-duckdb/src/test/java/io/kestra/plugin/jdbc/duckdb/DuckDbTest.java

Fixes : https://github.com/kestra-io/kestra/issues/4303

fix: support for DuckDB array

---

plugin-jdbc-snowflake/build.gradle
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/SnowflakeCLI.java
plugin-jdbc-snowflake/src/test/java/io/kestra/plugin/jdbc/snowflake/SnowflakeCLITest.java

add SnowflakeCLI task
closes #544

feat(snowflake): add SnowflakeCLI task

---

build.gradle
plugin-jdbc-as400/build.gradle
plugin-jdbc-duckdb/build.gradle
plugin-jdbc-oracle/build.gradle
plugin-jdbc-snowflake/build.gradle
plugin-jdbc-sqlite/build.gradle
plugin-jdbc-trino/build.gradle

chore(deps): update regular dependencies driver snowflake, trino, duckdb, oracle, sqlite

---

plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/SnowflakeInterface.java

fix(snowflake): privatekey auth did not work

---

plugin-jdbc-as400/src/main/java/io/kestra/plugin/jdbc/as400/Query.java
plugin-jdbc-db2/src/main/java/io/kestra/plugin/jdbc/db2/Queries.java
plugin-jdbc-db2/src/main/java/io/kestra/plugin/jdbc/db2/Query.java
plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Queries.java
plugin-jdbc-sqlite/src/main/java/io/kestra/plugin/jdbc/sqlite/Query.java
plugin-jdbc-sqlserver/src/main/java/io/kestra/plugin/jdbc/sqlserver/Queries.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQuery.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AutoCommitInterface.java

first part of #550
only doing the documentation depreciation, will remove conditional logic with Store later so it can be more tested/QA

chore: depreciate autocommit property

---

plugin-jdbc-snowflake/build.gradle
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/AbstractSnowflakeConnection.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Queries.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Query.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/RSAKeyPairUtils.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/SnowflakeCLI.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/SnowflakeInterface.java
plugin-jdbc-snowflake/src/main/java/io/kestra/plugin/jdbc/snowflake/Trigger.java
plugin-jdbc-snowflake/src/test/java/io/kestra/plugin/jdbc/snowflake/RSAKeyPairUtilsTest.java

R21 try do not merge

---

plugin-jdbc-mysql/src/test/java/io/kestra/plugin/jdbc/mysql/MysqlTest.java

Add test to cover all possible fetchType combination for MySQL updates
#531

test(mysql): cover all fetchType cases for MySQL update

---

plugin-jdbc-arrow-flight/build.gradle
plugin-jdbc-as400/build.gradle
plugin-jdbc-clickhouse/build.gradle
plugin-jdbc-clickhouse/src/main/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseCellConverter.java
plugin-jdbc-clickhouse/src/test/java/io/kestra/plugin/jdbc/clickhouse/ClickHouseTest.java
plugin-jdbc-druid/build.gradle
plugin-jdbc-duckdb/build.gradle
plugin-jdbc-duckdb/src/test/java/io/kestra/plugin/jdbc/duckdb/DuckDbTest.java
plugin-jdbc-mariadb/build.gradle
plugin-jdbc-mariadb/src/test/java/io/kestra/plugin/jdbc/mariadb/MariaDbTest.java
plugin-jdbc-mysql/src/test/java/io/kestra/plugin/jdbc/mysql/MysqlTest.java
plugin-jdbc-oracle/build.gradle
plugin-jdbc-oracle/src/test/java/io/kestra/plugin/jdbc/oracle/OracleTest.java
plugin-jdbc-pinot/build.gradle
plugin-jdbc-postgres/src/test/java/io/kestra/plugin/jdbc/postgresql/PgsqlTest.java
plugin-jdbc-sqlserver/build.gradle
plugin-jdbc-trino/build.gradle

Bump to last deps

---

build.gradle

feat(cicd): #4006 migrate sonatype to maven central

---

plugin-jdbc-clickhouse/build.gradle

fix(clickhouse): resolve conflicting deps

---

plugin-jdbc-sqlserver/src/test/java/io/kestra/plugin/jdbc/sqlserver/SqlServerTest.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQueries.java
plugin-jdbc/src/main/java/io/kestra/plugin/jdbc/AbstractJdbcQuery.java

fix(*): report size when results are empty

---

.github/setup-unit.sh
docker-compose-ci.yml

ci(): migrate from bitnami images

---

README.md

Linked Issue
Fixes #11725
fixing the social icons issue for safari browser
---
---

fixed the icoins to horizental for safari#11725
